version: 2

sources:
  - name: raw_instacart
    description: "Nguồn dữ liệu raw dùng cho đồ án"
    database: project-57a003b3-e918-4bc9-b43
    schema: dbt_dev_toni

    tables:
      - name: aisles
        description: "Chứa thông tin về các danh mục/quầy trong cửa hàng"
      - name: departments
        description: "Chứa thông tin về danh mục ngành hàng trong cửa hàng"
      - name: order_products_prior
        description: "Chứa thông tin về chi tiết sản phẩm trong các đơn prior"
      - name: order_products_train
        description: "Chứa thông tin về chi tiết sản phẩm trong các đơn train"
      - name: orders
        description: "Chứa thông tin về các đơn hàng của khách hàng"
      - name: products
        description: "Chứa thông tin về các sản phẩm được bán trong cửa hàng"
